#!/bin/bash

#SBATCH --tasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --time=12:00:00

cd $SLURM_SUBMIT_DIR

pwd; hostname; date

conda init bash
. ~/.bashrc
conda activate drugrank


model=$1
outd=$2
bs=$3
ae_path=$4
ae_dim=$5
fgen=$6
save_dir=$7
delta=${8}
score=${9}
depth=${10}
fold=${11}
gs=${12}
dataset=${13}
setup=${14}
epoch=${15}
alpha=${16}

data_folder="data/${dataset}/"
splits_path="${data_folder}/LCO/splits/"

aebs=(32 32 16 16 32)
aed=(128 32 64 128 128)


ae_dim=${aed[$fold]}
ae_bs=${aebs[$fold]}
ae_model="${ae_path}/all_bs_${ae_bs}_outd_${ae_dim}/fold_${fold}/"

cmds="--data_path ${data_folder}/final_list_auc.txt --smiles_path ${data_folder}/cmpd_smiles.txt --splits_path ${splits_path} --save_path ${save_dir} --pretrained_ae -ae_path ${ae_model} -ae_outd ${ae_dim} -e $epoch -mol_outd ${outd} -b ${bs} --cuda --model $model --delta $delta -score $score --setup $setup -gstep $gs"

if [[ $model == 'pairpushc' ]]; then
	cmds="$cmds --alpha $alpha -classc"
fi

if [[ $fgen == 'morgan_count' ]]; then
	echo "python src/cross_validate.py $cmds -fgen $fgen --only_fold $fold > ${save_dir}/result_${fold}.txt"
else
	python src/cross_validate.py $cmds --pooling $pool --message_steps $depth --only_fold $fold > $save_dir/result_${fold}.txt
fi